#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: stat rutorrents opt
  stat: path=/opt/appdata/rutorrents
  register: rutorrents_stat

- name: stat rutorrents
  stat: path=/mnt/rutorrents
  register: rutorrent_stat

- name: Deploy {{role_name}} Container
  docker_container:
    name: "{{role_name}}"
    image: "linuxserver/rutorrent"
    pull: yes
    cpu_shares: 256
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
      - "51413:51413"
      - "6881:6881/udp"
      - "5000:5000"
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/opt/appdata/rutorrent/config:/config"
      - "/mnt/unionfs:/unionfs"
      - "{{path.stdout}}/rutorrent/:/downloads"
      - /opt/appdata/{{role_name}}:/scripts
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started
    labels:
      traefik.enable: "true"
      traefik.frontend.redirect.entryPoint: "https"
      traefik.frontend.rule: "Host:{{role_name}}.{{domain.stdout}}"
      traefik.port: "{{intport}}"

###################################### REGEX Source: Desmonic @ CLOUDBOX.rocks
- name: "Wait for 10 Seconds"
  wait_for:
    timeout: 10

- name: Stop container to customize rtorrent.rc
  docker_container:
    name: rutorrent
    state: stopped
  ignore_errors: yes

- name: Change downloads directory
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^directory\s?='
    line: 'directory = /downloads/incoming'
    state: present
  ignore_errors: yes

- name: Disable DHT
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^dht\s?='
    line: 'dht = disable'
    state: present
  ignore_errors: yes

- name: Disable PEX
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^peer_exchange\s?='
    line: 'peer_exchange = no'
    state: present
  ignore_errors: yes

- name: Reduce min_peers
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^min_peers\s?='
    line: 'min_peers = 1'
    state: present
  ignore_errors: yes

- name: Increase max_uploads
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^max_uploads\s?='
    line: 'max_uploads = 1024'
    state: present
  ignore_errors: yes

- name: Disable check_hash
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^check_hash\s?='
    line: 'check_hash = no'
    state: present
  ignore_errors: yes

- name: Set upload_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^upload_rate\s?='
    line: 'upload_rate = 0'
    state: present
  ignore_errors: yes

- name: Set download_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^download_rate\s?='
    line: 'download_rate = 0'
    state: present
  ignore_errors: yes

- name: Set global upload_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^throttle.global_up.max_rate.set_kb\s?='
    line: 'throttle.global_up.max_rate.set_kb = 0'
    state: present
  ignore_errors: yes

- name: Set global download_rate to unlimited
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^throttle.global_down.max_rate.set_kb\s?='
    line: 'throttle.global_down.max_rate.set_kb = 0'
    state: present
  ignore_errors: yes

- name: Set max_open_files to 1024
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^network.max_open_files.set\s?='
    line: 'network.max_open_files.set = 1024'
    state: present
  ignore_errors: yes

- name: Set encryption parameter
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^encryption\s?='
    line: 'encryption = allow_incoming,enable_retry,prefer_plaintext'
    state: present
  ignore_errors: yes

- lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^max_downloads_global\s?='
    line: 'max_downloads_global = 1024'
    state: present
  ignore_errors: yes

- name: Set file_allocate to no
  lineinfile:
    path: "/opt/appdata/rutorrent/config/rtorrent/rtorrent.rc"
    regexp: '^system.file_allocate.set\s?='
    line: 'system.file_allocate.set = no'
    state: present
  ignore_errors: yes

- name: Set upload_max_filesize to 8M
  lineinfile:
    path: "/opt/appdata/rutorrent/config/php/php.ini"
    regexp: '^upload_max_filesize\s?='
    line: 'upload_max_filesize = 8M'
    state: present
  ignore_errors: yes

- name: Start container to apply changes
  docker_container:
    name: rutorrent
    state: started

- include_role:
    name: pgmend
