---
############ Directories
  - name: Create Basic Directories
    file: "path={{item}} state=directory mode=0775 owner=1000 group=1000 recurse=true"
    with_items:
      - /opt/appdata/plexguide
      - /mnt/unionfs/tv
      - /mnt/unionfs/movies
      - /mnt/unionfs/music
      - /mnt/unionfs/ebooks