#!/bin/bash
#
# [RClone Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
########### DRIVES
  - name: Check DRIVES Service
    stat:
      path: "/etc/systemd/system/drives.service"
    register: drives

  - name: Stop If DRIVES Service Running
    systemd: state=stopped name=unionfs
    when: drives.stat.exists

  - name: Main Line
    shell: "cat /var/plexguide/hd/combined"
    register: drives_var
    ignore_errors: True

  - name: Install UNIONFS Service
    template:
      src: drives.js2
      dest: /etc/systemd/system/drives.service 
      force: yes
#################################### REPLACE START
  - name: Replace Drives Line
    replace:
      path: /etc/systemd/system/drives.service
      regexp: replaceme
      replace: "{{drives_var.stdout}}"
#################################### REPLACE END

  - name: Daemon-Reload
    systemd: state=stopped name=drives daemon_reload=yes enabled=no

  - name: Start Unionfs
    systemd: state=started name=drives enabled=yes
    #when: drives.stat.exists