#!/bin/bash
#
# [Ansible Role]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: "Establishing SmoothStreams Username"
  shell: "cat /tmp/sstvuser"
  register: sstvuser

- name: "Establishing SmoothStreams Password"
  shell: "cat /tmp/sstvpwd"
  register: sstvpwd

- name: "Establishing SmoothStreams Service"
  shell: "cat /tmp/sstvservice"
  register: sstvservice

- name: "Establishing Server Timezone"
  shell: "cat /etc/timezone"
  register: sstvtimezone

- name: Stop and remove any existing container
  docker_container:
    name: sstvproxy
    state: absent
  ignore_errors: yes

- name: Deploy Critical Directories
  file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
  with_items:
    - "/opt/appdata/{{role_name}}"

- name: Deploy SSTVProxy Container
  docker_container:
    name: "{{role_name}}"
    image: "stokkes/sstvproxy"
    pull: yes
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
      - "{{ports.stdout}}8099:8099"
    volumes:
      - "/opt/appdata/{{role_name}}:/config"
      - "/etc/localtime:/etc/localtime:ro"
    cpu_shares: 256
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{sstvtimezone.stdout}}"
      YAP_USERNAME: "{{sstvuser.stdout}}"
      YAP_PASSWORD: "{{sstvpwd.stdout}}"
      YAP_SERVICE: "{{sstvservice.stdout}}"
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: always
    state: started

- include_role:
    name: pgmend
