#!/bin/bash
#
# [x2go Server]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705 & Deiteq & FlickerRate
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- include_vars: variables.yml

- include_role:
    name: pgmstart

- name: Remove x2go Container
  docker_container:
    name: x2go
    state: absent

- name: Deploy x2go Container
  docker_container:
    name: "{{role_name}}"
#    image: deiteq/dockerx2go
    image: kirkins/xubuntu16-x2go
    pull: yes
    cpu_shares: 512
    published_ports:
      - "{{ports.stdout}}{{extport}}:{{intport}}"
 #     - "2222:22"
    user: 0
    env:
      PUID: "1000"
      PGID: "1000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt:/mnt"
      - "/opt:/opt"  # Think about changing path for 2nd hd option!
      - "/tmp:/tmp"
 #     - "/mnt:/headless/Desktop/mnt:rw"
    networks:
      - name: plexguide
        aliases:
          - "{{role_name}}"
    restart_policy: unless-stopped
    state: started

- debug:
     msg: "  For SECURITY reasons - Please stop this container when not in use!  "
- debug:
     msg: "  Check x2go portainer log for dockerx password  "

- include_role:
    name: pgmend